rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  # - rbx-2.0
  # - jruby

env:
  - GEM=sunspot
  - GEM=sunspot_rails RAILS=2.3.16
  - GEM=sunspot_rails RAILS=3.0.20
  - GEM=sunspot_rails RAILS=3.1.10
  - GEM=sunspot_rails RAILS=3.2.11

# Limit the size of the matrix by only performing the most common builds
matrix:
  exclude:
    # Not supporting Ruby 1.8.7 + Rails >= 3
    - rvm: 1.8.7
      env: GEM=sunspot_rails RAILS=3.0.20
    - rvm: 1.8.7
      env: GEM=sunspot_rails RAILS=3.1.10
    - rvm: 1.8.7
      env: GEM=sunspot_rails RAILS=3.2.11
    - rvm: 1.9.3
      env: GEM=sunspot_rails RAILS=2.3.16
    # Not supporting Ruby 2.0 and Rails < 3
    - rvm: 2.0.0
      env: GEM=sunspot_rails RAILS=2.3.16
    - rvm: 2.0.0
      env: GEM=sunspot_rails RAILS=3.0.20
    - rvm: 2.0.0
      env: GEM=sunspot_rails RAILS=3.1.10

script:
  - ci/travis.sh
